POST http://localhost:3000/api/recipes
Content-Type: application/json

{
  "title": "Jam Sandwich",
  "description": "Two pieces of bread with some jam filling inside",
  "image": null,
  "ingredients": [
    "Bread",
    "Jam"
  ],
  "directions": [
    "Spread the jam on the slices of bread",
    "Join the breads together and enjoy!"
  ]
}