PUT http://localhost:3000/api/recipes/67c3fb09f8f2b6eee331834f
Content-Type: application/json

{
  "title": "Modified Jam Sandwich",
  "description": "Two pieces of bread with some jam filling inside",
  "ingredients": [
    "Bread",
    "Jam",
    "Pepper"
  ],
  "directions": [
    "Spread the jam on the slices of bread",
    "Join the breads together and enjoy!",
    "Sprinkle some pepper"
  ],
  "id": "67c3fb09f8f2b6eee331834f"
}